package main

import (
    "fmt"
    "os"
)

func showUsage() {
    fmt.Println("CBZ Converter - Convert image folders to CBZ comic book archives")
    fmt.Println()
    fmt.Println("USAGE:")
    fmt.Printf("  %s -input <dir> [-input <dir>...] -output <folder> [options]\n", os.Args[0])
    fmt.Println()
    fmt.Println("REQUIRED:")
    fmt.Println("  -input,  -i  string    Input directory (can be specified multiple times)")
    fmt.Println("  -output, -o  string    Output directory for CBZ files")
    fmt.Println()
    fmt.Println("OPTIONS:")
    fmt.Println("  -recursive, -r       Process subdirectories recursively (default: false)")
    fmt.Println("  -threads,   -j int   Number of concurrent threads (default: 4)")
    fmt.Println("  -dumb,      -d       Archive all files without filtering (default: false)")
    fmt.Println("  -help,      -h       Show this help message")
    fmt.Println("  -version,   -v       Show version information")
    fmt.Println()
    fmt.Println("EXAMPLES:")
    fmt.Println("  1. Recursive Mode:")
    fmt.Println("     Process every subdirectory inside root folders:")
    fmt.Printf("       %s -recursive -input ./mangas -output ./cbz\n", os.Args[0])
    fmt.Printf("       %s -recursive -input ./mangas -input ./fav-mangas -output ./cbz\n", os.Args[0])
    fmt.Println()
    fmt.Println("  2. Direct Mode (single specific folder):")
    fmt.Println("     Convert only the specified directory:")
    fmt.Printf("       %s -input \"./mangas/some manga\" -output ./cbz\n", os.Args[0])
    fmt.Println()
    fmt.Println("  3. Direct Mode (multiple specific folders):")
    fmt.Println("     Convert each specified directory (no recursion):")
    fmt.Printf("       %s -input \"./mangas/some manga\" -input \"./mangas/some manga part 2\" -output ./cbz\n", os.Args[0])
    fmt.Println()
    fmt.Println("  4. With additional options:")
    fmt.Printf("       %s -recursive -threads 8 -input ./mangas -output ./cbz\n", os.Args[0])
    fmt.Printf("       %s -dumb -input \"./raw/chapter 1\" -output ./archives\n", os.Args[0])
    fmt.Println()
    fmt.Println("MODES:")
    fmt.Println("  RECURSIVE (-recursive|-r):")
    fmt.Println("    Scans input directories and converts each subdirectory into a CBZ")
    fmt.Println("    Example: ./mangas/ contains [manga1/, manga2/, manga3/]")
    fmt.Println("             → Creates manga1.cbz, manga2.cbz, manga3.cbz")
    fmt.Println()
    fmt.Println("  DIRECT (default):")
    fmt.Println("    Converts the specified directories directly into CBZ files")
    fmt.Println("    Example: -input \"./mangas/manga1\"")
    fmt.Println("             → Creates manga1.cbz (only this folder)")
    fmt.Println()
    fmt.Println("  SMART (default):")
    fmt.Println("    Intelligently filters files to include:")
    fmt.Println("      • Image files (JPEG, PNG, GIF, WebP, HEIF, etc.)")
    fmt.Println("      • Text files (TXT, MD, NFO - metadata)")
    fmt.Println("      • Video files (MP4, AVI, MKV - supplementary content)")
    fmt.Println("      • Excludes: system files (.DS_Store, Thumbs.db), VCS (.git, .svn)")
    fmt.Println()
    fmt.Println("  DUMB (-dumb|-d):")
    fmt.Println("    Archives everything without any filtering")
}

